parser: network: fix comparison of undefined entries in the port map
Switching cmp_network_map() to use const references exposed an issue
where comparisonson where being done between maps without the entry
defined.

...Binary equality network port range
ERROR: Error hashing the following profile:
/t { network port=3456,
     network port=3457,
     network port=3458,
     network port=3459,
     network port=3460,
}

Binary equality network peer port range
ERROR: Error hashing the following profile:
/t { network peer=(port=3456),
     network peer=(port=3457),
     network peer=(port=3458),
     network peer=(port=3459),
     network peer=(port=3460),
}

The [] operator when accessing a map constructs a new entry when the
referenced entry doesn't exist. However the at() method throws an
exception. Switch to using an const_iterator instead of using at()
so we can detect which entry does't exist. While we could do this
with at() and catching the exceptions, with a try/catch around each
at() the iterator approach is a little cleaner.

The above equality test failure above occurs when both profiles are
mising the same family index resulting in an execption thrown from
the at() method, causing the hash files to not be created, and fail
the comparison.

Signed-off-by: John Johansen <john.johansen@canonical.com>