aa-notify: catch DBusException on too many events
If too many notifications get sent in a short time, we get a
DBusException:

    dbus.exceptions.DBusException: org.freedesktop.Notifications.Error.ExcessNotificationGeneration: Created too many similar notifications in quick succession

Unfortunately this exception also kills aa-notify.

This patch catches the exception, and displays the notification on
stderr. While this is not user-visible (and the user misses some
notifications), it at least prevents that aa-notify crashes
(= stopping all further notifications).

Fixes: https://gitlab.com/apparmor/apparmor/-/work_items/573
(cherry picked from commit 7f123b603e2361750a680893863684aa9ef8a6cf)
Signed-off-by: John Johansen <john.johansen@canonical.com>